name: 刷步数

on:
  # 每天 UTC 4:00 和 10:00 执行
  schedule:
    - cron: '0 4,10 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: 刷新小米运动步数
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip install --upgrade pip
          pip3 install requests
          python3 main.py
